### ISSUE TITLE
Link does not work (Zelda is sick of him)

### ISSUE THREAD

**Issue by vmeyet** [himmelarthur/central#3]
On the README.md, the last link to your website is broken. it links to https://github.com/himmelarthur/central/blob/master/arthurhimmel.com. whereas it seems you want to link to http://arthurhimmel.com.

<img alt='ex of broken link' src='http://g.recordit.co/wKshIExdYC.gif' width='500px' />
#### Why it matters
- [Broken Links, Pages, Images And 404s Hurt SEO And Affect Google Rankings](http://www.blizzardpress.com/404-errors-and-seo-rankings/)
- People want to know who you are

**Keep up the good work buddy**

![](http://www.quickmeme.com/img/12/12c72ed530dc842b501aa75a3e7a230c9143008e60329a93659e9feeb6905c28.jpg)

**Comment by himmelarthur** [comment]
Sigh... I guess hypertext links are like dark magic to me :(
